# Learn more about configuring your app at https://docs.shipready.dev/

client_id = 
name = "ShipReady"
handle = "shipready-app"
application_url = "https://throat-dedicated-mai-progress.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shipready-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://throat-dedicated-mai-progress.trycloudflare.com/auth/callback",
  "https://throat-dedicated-mai-progress.trycloudflare.com/auth/shopify/callback",
  "https://throat-dedicated-mai-progress.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://beer-copied-angeles-ordered.trycloudflare.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[app_proxy]
url = "https://throat-dedicated-mai-progress.trycloudflare.com/auth/callback"
subpath = "shipready-v0-1"
prefix = "apps"

[pos]
embedded = false
